# Generated by Django 3.1 on 2020-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='history',
            field=models.FloatField(default=0),
        ),
    ]
