# Generated by Django 3.1 on 2020-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20200813_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.FloatField(default=0),
        ),
    ]
